name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint-and-format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            - name: Install dependencies
              run: cd frontend && bun install

            - name: Run Biome Lint
              run: cd frontend && bunx biome lint --error-on-warning

            - name: Run Biome Format
              run: cd frontend && bunx biome format
