name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint-and-format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                go-version: '1.24.3'

            - name: Install dependencies
              run: bun install

            - name: Run Biome check
              run: bunx biome ci src/

            - name: Check Go formatting
              run: |
                cd server
                test -z $(go fmt ./...)
